apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-labels-to-files
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-labels-to-files
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-labels-to-files-pod
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - update
  - get

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: node-labels-to-files
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-labels-to-files
subjects:
- kind: ServiceAccount
  name: node-labels-to-files
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: node-labels-to-files-pod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-labels-to-files-pod
subjects:
- kind: ServiceAccount
  name: node-labels-to-files
  namespace: default

---

apiVersion: v1
kind: Pod
metadata:
  name: node-labels-to-files-pod
  labels:
    app: node-labels-to-files
spec:
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
  containers:
  - name: node-labels-to-files
    image: node-labels-to-files
    imagePullPolicy: Always
    command:
      - /usr/bin/node-labels-to-files
      - -v
      - "2"
    env:
      - name: DELETE_STALE_FILES
        value: "true"
      - name: MODE
        value: always
      - name: DIRECTORY
        value: /tmp/foo
      - name: NODENAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: HOST_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: SERVICE_ACCOUNT
        valueFrom:
          fieldRef:
            fieldPath: spec.serviceAccountName
    volumeMounts:
      - name: podinfo
        mountPath: /etc/podinfo
  serviceAccount: node-labels-to-files
  serviceAccountName: node-labels-to-files
